### ISSUE TITLE
Not working on arm

### ISSUE THREAD

**Issue by Exellent1988** [MycroftAI/docker-mycroft#62]
Hy i tryed to run this docker image on an arm processor, but its nmt stirting beacuse i guess the packadges inside are build for x86 /amd64?

and i can't build it from scratch beacause mimic is not availible on the repo for arm..

**Comment by TheLastProject** [comment]
Sounds like something @forslund would know more about

**Comment by forslund** [comment]
The desktop-repo has only x64 packages, I could add the arm package from http://repo.mycroft.ai (built for armhf if I recall correctly) I also have a package for arm64 if that's a better fit.

If you can verify that the arm package works I can just add them to the repo.

**Comment by Exellent1988** [comment]
yes the armhf package would be great :)

Am Mo., 23. März 2020 um 08:38 Uhr schrieb Åke <notifications@github.com>:

**Comment by kefor** [comment]
> 
> 
> The desktop-repo has only x64 packages, I could add the arm package from http://repo.mycroft.ai (built for armhf if I recall correctly) I also have a package for arm64 if that's a better fit.
> 
> If you can verify that the arm package works I can just add them to the repo.

Hi, i want to support this. How can I verify that the packages are working ?

**Comment by Exellent1988** [comment]
I will try it on my banapi m3 , and pi 2/3/4 ?

Am Sa., 28. März 2020 um 11:19 Uhr schrieb kefor <notifications@github.com>:

**Comment by bdcarr** [comment]
Hello, I'm trying to run this on a Pi 4b and would also like to help verify whether the arm package works. Not sure how to do that though.

**Comment by forslund** [comment]
I've now pushed armhf and arm64 mimic packages to the mycroft-desktop repo. Sorry for the delay. I'm not sure of the best way to test it however. Maybe you can manually install the package following the instructions here: https://forslund.github.io/mycroft-desktop-repo/

**Comment by kefor** [comment]
> 
> 
> I've now pushed armhf and arm64 mimic packages to the mycroft-desktop repo. Sorry for the delay. I'm not sure of the best way to test it however. Maybe you can manually install the package following the instructions here: https://forslund.github.io/mycroft-desktop-repo/

i could install mimic. apt list mimic shows the armhf mimic/unknown,now 1.3.0.1 armhf [installed] on a rasp 3b+

**Comment by rohm1** [comment]
I wish I had seen this thread the past week :/ Anyway, there still isn't an armhf Docker image available, so I thought I would share my Dockerfile. Of course based on the one available in this repo, just compiled mimic on the PI (and removed lots of files to keep the image as small as possible).

```
FROM raspbian/stretch

ENV TERM linux
ENV DEBIAN_FRONTEND noninteractive

# Install Server Dependencies for Mycroft
RUN set -x \
	&& sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list \
	&& apt-get update \
	&& apt-get -y install git python3 python3-pip locales sudo \
	&& pip3 install future msm \
	# Checkout Mycroft
	&& git clone https://github.com/MycroftAI/mycroft-core.git /opt/mycroft \
	&& cd /opt/mycroft \
	&& mkdir /opt/mycroft/skills \
	# git fetch && git checkout dev && \ this branch is now merged to master
	&& CI=true /opt/mycroft/./dev_setup.sh --allow-root \
	&& mkdir /opt/mycroft/scripts/logs \
	&& touch /opt/mycroft/scripts/logs/mycroft-bus.log \
	&& touch /opt/mycroft/scripts/logs/mycroft-voice.log \
	&& touch /opt/mycroft/scripts/logs/mycroft-skills.log \
	&& touch /opt/mycroft/scripts/logs/mycroft-audio.log \
	&& apt-get -y autoremove \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
	&& rm -rf /opt/mycroft/.git /opt/mycroft/.github /opt/mycroft/doc /opt/mycroft/test \
	&& mv /opt/mycroft/mimic /opt/mycroft/mimic.bak \
	&& mkdir /opt/mycroft/mimic \
	&& mv /opt/mycroft/mimic.bak/bin /opt/mycroft/mimic/ \
	&& mv /opt/mycroft/mimic.bak/lib /opt/mycroft/mimic/ \
	&& mv /opt/mycroft/mimic.bak/voices /opt/mycroft/mimic/ \
	&& rm -rf /opt/mycroft/mimic.bak

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR /opt/mycroft
COPY startup.sh /opt/mycroft
ENV PYTHONPATH $PYTHONPATH:/mycroft/ai

RUN echo "PATH=$PATH:/opt/mycroft/bin" >> $HOME/.bashrc \
        && echo "source /opt/mycroft/.venv/bin/activate" >> $HOME/.bashrc

RUN chmod +x /opt/mycroft/start-mycroft.sh \
	&& chmod +x /opt/mycroft/startup.sh

EXPOSE 8181

ENTRYPOINT "/opt/mycroft/startup.sh"
```

**Comment by forslund** [comment]
I tested the docker image with the newly uploaded mimic packages and it builds cleanly on armhf. Will test on arm64 later this week.

**Comment by mjkaye** [comment]
Just to add that the armhf mimic package also works for me. I have an armhf image over on [hub.docker.com/r/mjkaye/mycroft-debian-slim](https://hub.docker.com/r/mjkaye/mycroft-debian-slim). I also have an, as yet untested, arm64 image there if anyone wants to give it a try. Feedback is welcome.

**Comment by sirwolfgang** [comment]
Created an updated version based off @mjkaye https://github.com/sirwolfgang/docker-mycroft/tree/pi
